### ISSUE TITLE
[Bug] no Install

### ISSUE THREAD

**Issue by softweri** [Implex-ltd/Implex-generator#13]
go: github.com/Implex-ltd/implex/cmd/engine imports
        engine/internal/browser: package engine/internal/browser is not in std (C:\Program Files\Go\src\engine\internal\browser)
make: *** [Makefile:19: install] Error 1

**Comment by 0xF7A4C6** [comment]
First, respect the issue template.

**Comment by 0xF7A4C6** [comment]
Fixed in https://github.com/Implex-ltd/Implex-generator/commit/5441f302a6617f7c80765ad2012de402d116fb01.
