### ISSUE TITLE
[Bug] playwright.cmd: file does not exist

### ISSUE THREAD

**Issue by Kenil35** [Implex-ltd/Implex-generator#17]
### Question

**Description**
i got this error while runninr classs
**Context**
error :could not start driver: exec: "C:\\Users\\Class\\AppData\\Local\\ms-playwright-go\\1.35.1\\playwright.cmd": file does not exist

**What I've Tried**
If you've attempted any solutions or research, please describe what you've tried so far.

**Additional Information**
Any additional details, screenshots, or examples that might be relevant to your question.

### Related Issues (if any)
Any related issues or pull requests that might be relevant to your question.

**Comment by 0xF7A4C6** [comment]
Follow install step  at https://github.com/playwright-community/playwright-go.

**Comment by 0xF7A4C6** [comment]
Auto install will be added soon.
