### ISSUE TITLE
Element not found.

### ISSUE THREAD

**Issue by ijnrghjkdsmigywneig203** [Implex-ltd/Implex-generator#19]
2023/08/13 12:53:36 could not send message to server: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for locator('xpath=//iframe[contains(@title,\'title="Widget containing checkbox for hCaptcha security challenge"\')]')

This issue occurs when starting up the Engine.

**Comment by 0xF7A4C6** [comment]
Please respect default form.

**Comment by ijnrghjkdsmigywneig203** [comment]
2023/08/13 12:53:36 could not send message to server: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for locator('xpath=//iframe[contains(@title,\'title="Widget contenant une case à cocher pour le défi de sécurité hCaptcha"\')]')

This is the french alternative, both English and french do not work.
