### ISSUE TITLE
Checking Orbita archive Trace: Error: Archive has not been found. Please run script again.

### ISSUE THREAD

**Issue by Kenil35** [Implex-ltd/Implex-generator#3]
Checking Orbita archive
Trace: Error: Archive has not been found. Please run script again.

**Comment by 0xF7A4C6** [comment]
1. Try to follow @TwerkPacket steps.
2. If it don't work, opena issue on [official gologin repo](https://github.com/gologinapp/gologin/issues), the orbita archive os not managed by us.
